apiVersion: v1
kind: Pod
metadata:
  name: myweb
  labels:
    env: prod
    app: main
    tier: frontend
    owner: Artem_Stupak
spec:
  containers:
  - name: container-apache
    image: 0rtem/myk8sapp:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
