apiVersion: v1
kind: Pod
metadata:
  name: myweb
spec:
  containers:
  - name: container-apache
    image: 0rtem/myk8sapp:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
